/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FollowNFT__factory } from "./FollowNFT__factory";
export { IFollowNFT__factory } from "./IFollowNFT__factory";
