/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IContentBaseFollowV1Interface extends utils.Interface {
  functions: {
    "follow(uint256,uint256)": FunctionFragment;
    "getFollowCounts(uint256)": FunctionFragment;
    "getProfileContract()": FunctionFragment;
    "updateProfileContract(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "follow"
      | "getFollowCounts"
      | "getProfileContract"
      | "updateProfileContract"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "follow",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getFollowCounts",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getProfileContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateProfileContract",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "follow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFollowCounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProfileContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProfileContract",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IContentBaseFollowV1 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IContentBaseFollowV1Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    follow(
      followerId: PromiseOrValue<BigNumberish>,
      followeeId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getFollowCounts(
      profileId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    getProfileContract(overrides?: CallOverrides): Promise<[string]>;

    updateProfileContract(
      newContractAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  follow(
    followerId: PromiseOrValue<BigNumberish>,
    followeeId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getFollowCounts(
    profileId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  getProfileContract(overrides?: CallOverrides): Promise<string>;

  updateProfileContract(
    newContractAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    follow(
      followerId: PromiseOrValue<BigNumberish>,
      followeeId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getFollowCounts(
      profileId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    getProfileContract(overrides?: CallOverrides): Promise<string>;

    updateProfileContract(
      newContractAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    follow(
      followerId: PromiseOrValue<BigNumberish>,
      followeeId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getFollowCounts(
      profileId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProfileContract(overrides?: CallOverrides): Promise<BigNumber>;

    updateProfileContract(
      newContractAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    follow(
      followerId: PromiseOrValue<BigNumberish>,
      followeeId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getFollowCounts(
      profileId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getProfileContract(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateProfileContract(
      newContractAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
