/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace DataTypes {
  export type CreatePublishDataStruct = {
    visibility: PromiseOrValue<BigNumberish>;
    handle: PromiseOrValue<string>;
    imageURI: PromiseOrValue<string>;
    contentURI: PromiseOrValue<string>;
  };

  export type CreatePublishDataStructOutput = [
    number,
    string,
    string,
    string
  ] & {
    visibility: number;
    handle: string;
    imageURI: string;
    contentURI: string;
  };

  export type UpdatePublishDataStruct = {
    visibility: PromiseOrValue<BigNumberish>;
    imageURI: PromiseOrValue<string>;
    contentURI: PromiseOrValue<string>;
  };

  export type UpdatePublishDataStructOutput = [number, string, string] & {
    visibility: number;
    imageURI: string;
    contentURI: string;
  };
}

export interface ContentBasePublishInterface extends utils.Interface {
  functions: {
    "createPublish(string,(uint8,string,string,string))": FunctionFragment;
    "updatePublish(uint256,string,(uint8,string,string))": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "createPublish" | "updatePublish"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createPublish",
    values: [PromiseOrValue<string>, DataTypes.CreatePublishDataStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePublish",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      DataTypes.UpdatePublishDataStruct
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "createPublish",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePublish",
    data: BytesLike
  ): Result;

  events: {
    "PublishCreated(uint256,address)": EventFragment;
    "PublishUpdated(uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "PublishCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PublishUpdated"): EventFragment;
}

export interface PublishCreatedEventObject {
  tokenId: BigNumber;
  owner: string;
}
export type PublishCreatedEvent = TypedEvent<
  [BigNumber, string],
  PublishCreatedEventObject
>;

export type PublishCreatedEventFilter = TypedEventFilter<PublishCreatedEvent>;

export interface PublishUpdatedEventObject {
  tokenId: BigNumber;
  owner: string;
}
export type PublishUpdatedEvent = TypedEvent<
  [BigNumber, string],
  PublishUpdatedEventObject
>;

export type PublishUpdatedEventFilter = TypedEventFilter<PublishUpdatedEvent>;

export interface ContentBasePublish extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ContentBasePublishInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createPublish(
      uri: PromiseOrValue<string>,
      createPublishData: DataTypes.CreatePublishDataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updatePublish(
      tokenId: PromiseOrValue<BigNumberish>,
      uri: PromiseOrValue<string>,
      updatePublishData: DataTypes.UpdatePublishDataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  createPublish(
    uri: PromiseOrValue<string>,
    createPublishData: DataTypes.CreatePublishDataStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updatePublish(
    tokenId: PromiseOrValue<BigNumberish>,
    uri: PromiseOrValue<string>,
    updatePublishData: DataTypes.UpdatePublishDataStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createPublish(
      uri: PromiseOrValue<string>,
      createPublishData: DataTypes.CreatePublishDataStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updatePublish(
      tokenId: PromiseOrValue<BigNumberish>,
      uri: PromiseOrValue<string>,
      updatePublishData: DataTypes.UpdatePublishDataStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "PublishCreated(uint256,address)"(
      tokenId?: null,
      owner?: null
    ): PublishCreatedEventFilter;
    PublishCreated(tokenId?: null, owner?: null): PublishCreatedEventFilter;

    "PublishUpdated(uint256,address)"(
      tokenId?: null,
      owner?: null
    ): PublishUpdatedEventFilter;
    PublishUpdated(tokenId?: null, owner?: null): PublishUpdatedEventFilter;
  };

  estimateGas: {
    createPublish(
      uri: PromiseOrValue<string>,
      createPublishData: DataTypes.CreatePublishDataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updatePublish(
      tokenId: PromiseOrValue<BigNumberish>,
      uri: PromiseOrValue<string>,
      updatePublishData: DataTypes.UpdatePublishDataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createPublish(
      uri: PromiseOrValue<string>,
      createPublishData: DataTypes.CreatePublishDataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updatePublish(
      tokenId: PromiseOrValue<BigNumberish>,
      uri: PromiseOrValue<string>,
      updatePublishData: DataTypes.UpdatePublishDataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
