/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contentBaseMainSol from "./ContentBaseMain.sol";
export type { contentBaseMainSol };
export type { ContentBaseProfile } from "./ContentBaseProfile";
