/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ILikeNFT__factory } from "./ILikeNFT__factory";
export { LikeNFT__factory } from "./LikeNFT__factory";
